### ISSUE TITLE
python2.7: ctypes.utils.find_library fails due to missing dependencies

### ISSUE THREAD

**Issue by evanj** [GoogleContainerTools/distroless#150]
The Python Standard Library's `ctypes.utils.find_library("c")` fails because it attempts to execute two programs. This causes gunicorn to not work (see the stack trace below). The "real" fix is to install `ldconfig` and generate the `/etc/ld.so.cache` file somehow. However, it also "works" for this specific case if you add `dash` to the container image. This is ugly, but gunicorn is pretty widely used, so it would be nice if it worked.

For details, a reproduction, and some examples of how I fixed this, see https://github.com/evanj/pydistroless_ctypes

The trace back I got when running gunicorn in a distroless python2.7 image is:

```
Traceback (most recent call last):
  File "/tmp/install/gunicorn-19.7.1-py2.py3-none-any.whl.9d2a2d914e9838232744d125e8d8a41509c11c9d/gunicorn-19.7.1-py2.py3-none-any.whl/gunicorn/util.py", line 134, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/install/gunicorn-19.7.1-py2.py3-none-any.whl.9d2a2d914e9838232744d125e8d8a41509c11c9d/gunicorn-19.7.1-py2.py3-none-any.whl/gunicorn/workers/sync.py", line 16, in <module>
    import gunicorn.http.wsgi as wsgi
  File "/tmp/install/gunicorn-19.7.1-py2.py3-none-any.whl.9d2a2d914e9838232744d125e8d8a41509c11c9d/gunicorn-19.7.1-py2.py3-none-any.whl/gunicorn/http/wsgi.py", line 24, in <module>
    from ._sendfile import sendfile
  File "/tmp/install/gunicorn-19.7.1-py2.py3-none-any.whl.9d2a2d914e9838232744d125e8d8a41509c11c9d/gunicorn-19.7.1-py2.py3-none-any.whl/gunicorn/http/_sendfile.py", line 27, in <module>
    _libc = ctypes.CDLL(ctypes.util.find_library("c"), use_errno=True)
  File "/usr/lib/python2.7/ctypes/util.py", line 285, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python2.7/ctypes/util.py", line 103, in _findLib_gcc
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by greggdonovan** [comment]
I hit this same issue trying to run a gunicorn app via `py_image`. Thanks for the workaround, @evanj. Much easier than installing gcc on top of the distroless image. :)

**Comment by pcn** [comment]
In addition, the URI module ends up running afoul of this.

**Comment by joshdk** [comment]
I hit the same issue when attempting to import [atdt/monotonic](https://github.com/atdt/monotonic) inside of `gcr.io/distroless/python2.7`.

Internally, it calls `ctypes.util.find_library('c')` and `ctypes.util.find_library('rt')`, which both fail in the above fashion.

I made [joshdk/distroless-monotonic-repro](https://github.com/joshdk/distroless-monotonic-repro) as a minimal repro example. Hope this helps!

**Comment by raliste** [comment]
Any ETA to update the images?

**Comment by evanj** [comment]
My understanding is that the images get published on every merge to master. The latest versions already include these changes.
