### ISSUE TITLE
python2.7: openssl cannot find root certificates (CERTIFICATE_VERIFY_FAILED)

### ISSUE THREAD

**Issue by evanj** [GoogleContainerTools/distroless#155]
`openssl s_client` and Python programs that verify SSL certificates fail. The base distroless image writes `/etc/ssl/certs/ca-certificates.crt`. However, the `openssl` command line tool, and libraries that link against `libssl` like Python by search for hashed certificates in `/usr/lib/ssl/certs`, which I believe are normally created at install time by the `c_rehash` command. These do not exist in the base image.

As a workaround, you can set `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` to get this to work. This should probably be added to the base image. A slightly better fix would be to generate the correct symlinks in the base image, so correct operation does not depend on the environment variables. See the example using `rules_docker`'s `py_image`: https://github.com/evanj/pydistroless_ssl

## Reproducing the bug and additional details

The minimal reproduction is: `docker run --entrypoint=openssl gcr.io/distroless/python2.7:latest s_client -quiet -connect google.com:443`

The output is:

```
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify error:num=20:unable to get local issuer certificate
```

This shows that it was unable to verify the certificate. Setting the `SSL_CERT_FILE` environment variable "fixes" it `docker run --env SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt --entrypoint=openssl gcr.io/distroless/python2.7:latest s_client -quiet -connect google.com:443`

```
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify return:1
depth=1 C = US, O = Google Inc, CN = Google Internet Authority G2
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google Inc, CN = *.google.com
verify return:1
```

Running this program using Distroless's python2.7 image:

```python
import urllib2
urllib2.urlopen('https://www.google.com/')
```

Produces the following error:

```
Traceback (most recent call last):
  File "/app/fetch_image.binary.runfiles/__main__/fetch.py", line 4, in <module>
    fh = urllib2.urlopen('https://www.google.com/')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
```

**Comment by evanj** [comment]
This bug should be closed! It was fixed in #200. I just verified it with the built images:

```
docker run -ti --rm gcr.io/distroless/base@sha256:a26dde6863dd8b0417d7060c990abe85c1d2481541568445e82b46de9452cf0c openssl s_client -strict -verify_return_error -connect www.google.com:443
```

Prints: `Verify return code: 0 (ok)`. The previous version printed: `Verify return code: 20 (unable to get local issuer certificate)`


The Python image works as well, tested with:

```
docker run -ti --rm gcr.io/distroless/python2.7@sha256:931ed7d543b76baec0ef460d4a98bf28dfce67fcf7949c051d6c0543db6375a2 -c "import urllib2; urllib2.urlopen('https://www.google.com/'); print 'ok'"
```
