### ISSUE TITLE
Clean build of all targets fails building python2.7

### ISSUE THREAD

**Issue by jharveysmith** [GoogleContainerTools/distroless#275]
OS: Mac OSX Mojave 10.14.2 (18C54)
Bazel: 0.20.0-homebrew
Java: openjdk version "11.0.1" 2018-10-16
Docker: 18.09.0 Community

I had to add the following line to `.bazelrc`:
`build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8`
to avoid the `Unrecognized VM option 'CompactStrings'` error that comes from using a newer bazel.

Here is the output:
```bash
$ bazel build --cpu='darwin' --compiler='compiler' //...
INFO: Invocation ID: 7d809323-5a8e-4a2b-9993-b22850e9c55c
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed 83 targets (0 packages loaded, 11314 targets configured).
INFO: Found 83 targets...
INFO: From ImageLayer base/static-layer.tar:
Duplicate file in archive: ./etc/os-release, picking first occurrence
INFO: From ImageLayer base/static-layer.tar [for host]:
Duplicate file in archive: ./etc/os-release, picking first occurrence
INFO: From ImageLayer experimental/python2.7/python27-layer.tar [for host]:
Duplicate file in archive: ./var/lib/dpkg/status.d/libpython2, picking first occurrence
INFO: From ImageLayer experimental/python3/python3-layer.tar:
Duplicate file in archive: ./var/lib/dpkg/status.d/libssl1, picking first occurrence
Duplicate file in archive: ./var/lib/dpkg/status.d/libpython3, picking first occurrence
INFO: From ImageLayer experimental/python2.7/debug-layer.tar:
Duplicate file in archive: ./var/lib/dpkg/status.d/libpython2, picking first occurrence
INFO: From ImageLayer experimental/python2.7/python27-layer.tar:
Duplicate file in archive: ./var/lib/dpkg/status.d/libpython2, picking first occurrence
INFO: From ImageLayer experimental/dotnet/dotnet-layer.tar:
Duplicate file in archive: ./var/lib/dpkg/status.d/libldap, picking first occurrence
Duplicate file in archive: ./var/lib/dpkg/status.d/libsasl2, picking first occurrence
ERROR: /private/tmp/distroless/experimental/python2.7/BUILD:64:1: Executing genrule //experimental/python2.7:ld_so_cache_new failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache", line 53, in <module>
    main()
  File "bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache", line 45, in main
    subprocess.check_call(docker_command, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('docker', 'run', '--read-only', '--interactive', '--rm', '--mount=type=bind,source=/var/folders/24/b89zvxks18n7sg07p0ctf6s80000gn/T/tmpazN8Wg,destination=/output', '--entrypoint=/sbin/ldconfig', 'bazel/experimental/python2.7:python27', '-C', '/output/ld.so.cache')' returned non-zero exit status 125
loading image /private/var/tmp/_bazel_jeff/b6f219c7d9550ff8ba38ed791d8c5055/sandbox/darwin-sandbox/61/execroot/distroless/bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache.runfiles/distroless/experimental/python2.7/python27 ...
Loaded image ID: sha256:290f22b46d4a66ece4e99d2b69ef9d4b994d5b3733290feee13b4da47f154189
Tagging 290f22b46d4a66ece4e99d2b69ef9d4b994d5b3733290feee13b4da47f154189 as bazel/experimental/python2.7:python27
running docker image bazel/experimental/python2.7:python27 ...
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/folders/24/b89zvxks18n7sg07p0ctf6s80000gn/T/tmpazN8Wg.
See 'docker run --help'.
INFO: Elapsed time: 17.243s, Critical Path: 15.12s
INFO: 95 processes: 93 darwin-sandbox, 2 worker.
FAILED: Build did NOT complete successfully
```

The directory `/var/folders/24/b89zvxks18n7sg07p0ctf6s80000gn/T/tmpazN8Wg` doesn't exist and I am having some trouble finding how it should have been created.
Running the failed docker command above, but substituting in an existing directory works and leaves behind an `ld.so.cache` as expected.

**Comment by chanseokoh** [comment]
The error message is coming from the Docker daemon. As this is a Docker issue, I'll close this. Note a lot of people on Mac are building images without an issue.

**Comment by briandealwis** [comment]
FTR: Docker on Mac only allows mounting file systems from a specific set of directories (`--mount` or `-v`).  This list of directories is configured via Docker's _Preferences > Resources > File Sharing_.  The `experimental/python2.7/generate_ldconfig_cache.py` script creates a temporary directory:

https://github.com/GoogleContainerTools/distroless/blob/3c6e10c21f508699c5ef7c84dee2ecc08bc8d5a3/experimental/python2.7/generate_ldconfig_cache.py#L35-L36

This call creates the temporary directory under the location pointed to by the TMPDIR environment variable.  The default `TMPDIR` is under `/var/folders/mx` (canonicalized to `/private/var/folders/mx`), which is not included in Docker's default file shares.

One way to verify this is to run Docker and to try to mount $TMPDIR in the container:
```console
$ docker run -it --rm --entrypoint /bin/sh -v $TMPDIR:/foo busybox
docker: Error response from daemon: Mounts denied: 
The path /var/folders/mx/_6wvyq4n3psb4nj95d8ycpv80000gn/T
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

But I can't seem to add `/var/folders/mx` to Docker's list of accepted file shares as it canonicalizes paths and so adds `/private/var/folders/mx`.  The daemon doesn't use canonicalized paths though in its matching. So the easiest solution is to define `TMPDIR` to some location that is in Docker's list of accepted file shares.
```console
$ TMPDIR=$HOME/tmp bazel build --cpu=darwin ...
```
