### ISSUE TITLE
Unable to build nodejs example

### ISSUE THREAD

**Issue by elsbrock** [GoogleContainerTools/distroless#523]
Hi,

I am new to Bazel and was trying to build the nodejs example. Basically what I did is the following:

Run `bazel build :hello` from the examples/nodejs directory on the clean repo. This failed with the following error:

<details><summary>Logs</summary><p>

```
$ bazel build :hello
INFO: Repository debian10_security instantiated at:                                                                                                                                                    
  no stack (--record_rule_instantiation_callstack not enabled)                                                                                                                                         
Repository rule _dpkg_src defined at:                                                                                                                                                                  
  /home/ubuntu/src/github.com/GoogleContainerTools/distroless/package_manager/dpkg.bzl:55:28: in <toplevel>                                                                                            
ERROR: An error occurred during the fetch of repository 'debian10_security':                                                                                                                           
   dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par, ...)": No su
ch file or directory                                                                                                                                                                                   
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --download-and-extract-only=True --mirror-url= --arch= --distro= --snapshot= --packages-gz-url=
https://snapshot.debian.org/archive/debian-security/20200424T130133Z//dists/buster/updates/main/binary-amd64/Packages.gz --package-prefix=https://snapshot.debian.org/archive/debian-security/20200424T
130133Z/ --sha256=65dab8d4b9c68d6d1726089092940e4c80a7e0d7151dacd9ec6b4cf6bd1f573b)                                                                                                                    
ERROR: /home/ubuntu/src/github.com/GoogleContainerTools/distroless/experimental/nodejs/BUILD:5:17: error loading package 'cc': Encountered error while reading extension file 'file/packages.bzl': no s
uch package '@package_bundle_debian10//file': no such package '@debian10_security//file': dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/ubuntu/src/github.com/
GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par, ...)": No such file or directory                                                                                            
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --download-and-extract-only=True --mirror-url= --arch= --distro= --snapshot= --packages-gz-url=
https://snapshot.debian.org/archive/debian-security/20200424T130133Z//dists/buster/updates/main/binary-amd64/Packages.gz --package-prefix=https://snapshot.debian.org/archive/debian-security/20200424T
130133Z/ --sha256=65dab8d4b9c68d6d1726089092940e4c80a7e0d7151dacd9ec6b4cf6bd1f573b) and referenced by '//experimental/nodejs:nodejs'                                                                   
ERROR: Analysis of target '//examples/nodejs:hello' failed; build aborted: Analysis failed                                                                                                             
INFO: Elapsed time: 40.148s                                                                                                                                                                            
INFO: 0 processes.                                                                                                                                                                                     
FAILED: Build did NOT complete successfully (27 packages loaded, 6478 targets configured)                                                                                                              
    Fetching @com_github_google_go_containerregistry; Restarting. 18s                                                                                                                                  
    Fetching @bazel_gazelle_go_repository_tools; fetching 17s                                                                                                                                          
    Fetching @com_github_pkg_errors; Restarting.                                                                                                                                                       
    Fetching @package_bundle_debian10; Restarting.                                             
```
</p></details>

After some research I understood that I need to manually build `dpkg_parser.par`. So I did the following:

<details><summary>Logs</summary><p>

```
$ bazel build //package_manager:dpkg_parser
INFO: Build option --host_force_python has changed, discarding analysis cache.                                                                                                                         
INFO: Analyzed target //package_manager:dpkg_parser (1 packages loaded, 348 targets configured).                                                                                                       
INFO: Found 1 target...                                                                                                                                                                                
Target //package_manager:dpkg_parser up-to-date:                                                                                                                                                       
  bazel-bin/package_manager/dpkg_parser                                                                                                                                                                
INFO: Elapsed time: 5.810s, Critical Path: 1.35s                                                                                                                                                       
INFO: 0 processes.                                                                                                                                                                                     
INFO: Build completed successfully, 4 total actions 
```
</p></details>

I then tried to build the `hello` target again, now it failed with a different error:

<details><summary>Logs</summary><p>

```
$ bazel build :hello
INFO: Repository debian10_security instantiated at:                                                                                                                                                    
  no stack (--record_rule_instantiation_callstack not enabled)                                                                                                                                         
Repository rule _dpkg_src defined at:                                                                                                                                                                  
  /home/ubuntu/src/github.com/GoogleContainerTools/distroless/package_manager/dpkg.bzl:55:28: in <toplevel>                                                                                            
ERROR: An error occurred during the fetch of repository 'debian10_security':                                                                                                                           
   dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par, ...)": No su
ch file or directory                                                                                                                                                                                   
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --download-and-extract-only=True --mirror-url= --arch= --distro= --snapshot= --packages-gz-url=
https://snapshot.debian.org/archive/debian-security/20200424T130133Z//dists/buster/updates/main/binary-amd64/Packages.gz --package-prefix=https://snapshot.debian.org/archive/debian-security/20200424T
130133Z/ --sha256=65dab8d4b9c68d6d1726089092940e4c80a7e0d7151dacd9ec6b4cf6bd1f573b)                                                                                                                    
ERROR: /home/ubuntu/src/github.com/GoogleContainerTools/distroless/experimental/nodejs/BUILD:5:17: error loading package 'cc': Encountered error while reading extension file 'file/packages.bzl': no s
uch package '@package_bundle_debian10//file': no such package '@debian10_security//file': dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/ubuntu/src/github.com/
GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par, ...)": No such file or directory                                                                                            
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --download-and-extract-only=True --mirror-url= --arch= --distro= --snapshot= --packages-gz-url=
https://snapshot.debian.org/archive/debian-security/20200424T130133Z//dists/buster/updates/main/binary-amd64/Packages.gz --package-prefix=https://snapshot.debian.org/archive/debian-security/20200424T
130133Z/ --sha256=65dab8d4b9c68d6d1726089092940e4c80a7e0d7151dacd9ec6b4cf6bd1f573b) and referenced by '//experimental/nodejs:nodejs'                                                                   
ERROR: Analysis of target '//examples/nodejs:hello' failed; build aborted: Analysis failed                                                                                                             
INFO: Elapsed time: 9.662s                                                                                                                                                                             
INFO: 0 processes.                                                                                                                                                                                     
FAILED: Build did NOT complete successfully (2 packages loaded, 1744 targets configured)                                                                                                               
    Fetching @com_github_google_go_containerregistry; Restarting. 8s                                                                                                                                   
    Fetching @bazel_gazelle_go_repository_tools; fetching 8s                                                                                                                                           
    Fetching @com_github_pkg_errors; Restarting. 8s                                                                                                                                          
    Fetching @package_bundle_debian10; Restarting.              
``` 

</p></details>

So for some reason the `dpkg_parser.par` file is not there, but the `bazel-bin/package_manager` folder contained a `dpkg_parser` Python file. Feeling lucky I linked this to `dpkg_parser.par` and reran the build:

<details><summary>Logs</summary><p>

```
$ bazel build :hello
INFO: Repository package_bundle_debian10 instantiated at:                                                                                                                                              
  no stack (--record_rule_instantiation_callstack not enabled)                                                                                                                                         
Repository rule _dpkg_list defined at:                                                                                                                                                                 
  /home/ubuntu/src/github.com/GoogleContainerTools/distroless/package_manager/dpkg.bzl:23:29: in <toplevel>                                                                                            
ERROR: An error occurred during the fetch of repository 'package_bundle_debian10':                                                                                                                     
   dpkg_parser command failed: Traceback (most recent call last):                                                                                                                                      
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 222, in <module>                   
    main()                                                                                                                                                                                             
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 75, in main                        
    download_dpkg(args.package_files, args.packages, args.workspace_name)                                                                                                                              
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 105, in download_dpkg              
    download_and_save(pkg_name, pkg[FILENAME_KEY], out_file)                                                                                                                                           
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 131, in download_and_save          
    remaining_bytes = int(res.info().getheader("Content-Length"))                                                                                                                                      
AttributeError: 'HTTPMessage' object has no attribute 'getheader'                                                                                                                                      
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --package-files /home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/extern
al/debian10_security/file/Packages.json,/home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/external/debian10/file/Packages.json --packages libc6,base-files,ca-certificates,opens
sl,libssl1.1,libbz2-1.0,libdb5.3,libffi6,liblzma5,libexpat1,libreadline7,libsqlite3-0,mime-support,netbase,readline-common,tzdata,libgcc1,libgomp1,libstdc++6,zlib1g,libjpeg62-turbo,libpng16-16,liblcm
s2-2,libfreetype6,fonts-dejavu-core,fontconfig-config,libfontconfig1,libuuid1,openjdk-11-jre-headless,openjdk-11-jdk-headless,dash,libc-bin,libpython2.7-minimal,libpython2.7-stdlib,python2.7-minimal,
libmpdec2,libpython3.7-minimal,libpython3.7-stdlib,libtinfo6,libuuid1,libncursesw6,python3-distutils,python3.7-minimal,libcurl4,libgssapi-krb5-2,libicu63,liblttng-ust0,libssl1.1,libunwind8,libuuid1,z
lib1g,curl,libcomerr2,libidn2-0,libk5crypto3,libkrb5-3,libldap-2.4-2,libldap-common,libsasl2-2,libnghttp2-14,libpsl5,librtmp1,libssh2-1,libkeyutils1,libkrb5support0,libunistring2,libgnutls30,libgmp10
,libhogweed4,libidn11,libnettle6,libp11-kit0,libffi6,libtasn1-6,libsasl2-modules-db,libgcrypt20,libgpg-error0,libacl1,libattr1,libselinux1,libpcre3,libbz2-1.0,liblzma5 --workspace-name package_bundle
_debian10)
ERROR: /home/ubuntu/src/github.com/GoogleContainerTools/distroless/experimental/nodejs/BUILD:5:17: //experimental/nodejs:nodejs depends on //cc:cc in repository @ which failed to fetch. no such packa
ge '@package_bundle_debian10//file': dpkg_parser command failed: Traceback (most recent call last):
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 222, in <module>
    main()
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 75, in main
    download_dpkg(args.package_files, args.packages, args.workspace_name)
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 105, in download_dpkg
    download_and_save(pkg_name, pkg[FILENAME_KEY], out_file)
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 131, in download_and_save
    remaining_bytes = int(res.info().getheader("Content-Length"))
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --package-files /home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/extern
al/debian10_security/file/Packages.json,/home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/external/debian10/file/Packages.json --packages libc6,base-files,ca-certificates,opens
sl,libssl1.1,libbz2-1.0,libdb5.3,libffi6,liblzma5,libexpat1,libreadline7,libsqlite3-0,mime-support,netbase,readline-common,tzdata,libgcc1,libgomp1,libstdc++6,zlib1g,libjpeg62-turbo,libpng16-16,liblcm
s2-2,libfreetype6,fonts-dejavu-core,fontconfig-config,libfontconfig1,libuuid1,openjdk-11-jre-headless,openjdk-11-jdk-headless,dash,libc-bin,libpython2.7-minimal,libpython2.7-stdlib,python2.7-minimal,
libmpdec2,libpython3.7-minimal,libpython3.7-stdlib,libtinfo6,libuuid1,libncursesw6,python3-distutils,python3.7-minimal,libcurl4,libgssapi-krb5-2,libicu63,liblttng-ust0,libssl1.1,libunwind8,libuuid1,z
lib1g,curl,libcomerr2,libidn2-0,libk5crypto3,libkrb5-3,libldap-2.4-2,libldap-common,libsasl2-2,libnghttp2-14,libpsl5,librtmp1,libssh2-1,libkeyutils1,libkrb5support0,libunistring2,libgnutls30,libgmp10
,libhogweed4,libidn11,libnettle6,libp11-kit0,libffi6,libtasn1-6,libsasl2-modules-db,libgcrypt20,libgpg-error0,libacl1,libattr1,libselinux1,libpcre3,libbz2-1.0,liblzma5 --workspace-name package_bundle
_debian10)
ERROR: Analysis of target '//examples/nodejs:hello' failed; build aborted: Analysis failed
INFO: Elapsed time: 60.846s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2471 targets configured)
    currently loading: cc
    Fetching @com_github_google_go_containerregistry; Restarting. 59s
    Fetching @bazel_gazelle_go_repository_tools; fetching 59s
    Fetching @com_github_pkg_errors; Restarting. 59s
```
</p></details> 

Now that error seems to be related to the Python version. On my system both Python versions are available, but 2 is the default:

<details><summary>Logs</summary><p>

```
$ python --version
Python 2.7.17
$ python2 --version
Python 2.7.17
$ python3 --version
Python 3.6.9
```
</p></details>

I re-ran using `--host_force_python=2`, sadly to no avail:

<details><summary>Logs</summary><p>

``` 
$ bazel build --verbose_failures --host_force_python=py2 hello 
INFO: Repository package_bundle_debian10 instantiated at:                                                                                                                                              
  no stack (--record_rule_instantiation_callstack not enabled)                                                                                                                                         
Repository rule _dpkg_list defined at:                                                                                                                                                                 
  /home/ubuntu/src/github.com/GoogleContainerTools/distroless/package_manager/dpkg.bzl:23:29: in <toplevel>                                                                                            
ERROR: An error occurred during the fetch of repository 'package_bundle_debian10':                                                                                                                     
   dpkg_parser command failed: Traceback (most recent call last):                                                                                                                                      
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 222, in <module>                   
    main()                                                                                                                                                                                             
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 75, in main                
    download_dpkg(args.package_files, args.packages, args.workspace_name)
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 105, in download_dpkg      
    download_and_save(pkg_name, pkg[FILENAME_KEY], out_file)
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 131, in download_and_save
    remaining_bytes = int(res.info().getheader("Content-Length"))
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --package-files /home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/extern
al/debian10_security/file/Packages.json,/home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/external/debian10/file/Packages.json --packages libc6,base-files,ca-certificates,opens
sl,libssl1.1,libbz2-1.0,libdb5.3,libffi6,liblzma5,libexpat1,libreadline7,libsqlite3-0,mime-support,netbase,readline-common,tzdata,libgcc1,libgomp1,libstdc++6,zlib1g,libjpeg62-turbo,libpng16-16,liblcm
s2-2,libfreetype6,fonts-dejavu-core,fontconfig-config,libfontconfig1,libuuid1,openjdk-11-jre-headless,openjdk-11-jdk-headless,dash,libc-bin,libpython2.7-minimal,libpython2.7-stdlib,python2.7-minimal,
libmpdec2,libpython3.7-minimal,libpython3.7-stdlib,libtinfo6,libuuid1,libncursesw6,python3-distutils,python3.7-minimal,libcurl4,libgssapi-krb5-2,libicu63,liblttng-ust0,libssl1.1,libunwind8,libuuid1,z
lib1g,curl,libcomerr2,libidn2-0,libk5crypto3,libkrb5-3,libldap-2.4-2,libldap-common,libsasl2-2,libnghttp2-14,libpsl5,librtmp1,libssh2-1,libkeyutils1,libkrb5support0,libunistring2,libgnutls30,libgmp10
,libhogweed4,libidn11,libnettle6,libp11-kit0,libffi6,libtasn1-6,libsasl2-modules-db,libgcrypt20,libgpg-error0,libacl1,libattr1,libselinux1,libpcre3,libbz2-1.0,liblzma5 --workspace-name package_bundle
_debian10)
ERROR: /home/ubuntu/src/github.com/GoogleContainerTools/distroless/experimental/nodejs/BUILD:5:17: //experimental/nodejs:nodejs depends on //cc:cc in repository @ which failed to fetch. no such packa
ge '@package_bundle_debian10//file': dpkg_parser command failed: Traceback (most recent call last):
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 222, in <module>
    main()
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 75, in main
    download_dpkg(args.package_files, args.packages, args.workspace_name)
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 105, in download_dpkg
    download_and_save(pkg_name, pkg[FILENAME_KEY], out_file)
  File "/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.runfiles/distroless/package_manager/dpkg_parser.py", line 131, in download_and_save
    remaining_bytes = int(res.info().getheader("Content-Length"))
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
 (/home/ubuntu/src/github.com/GoogleContainerTools/distroless/bazel-bin/package_manager/dpkg_parser.par --package-files /home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/extern
al/debian10_security/file/Packages.json,/home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/external/debian10/file/Packages.json --packages libc6,base-files,ca-certificates,opens
sl,libssl1.1,libbz2-1.0,libdb5.3,libffi6,liblzma5,libexpat1,libreadline7,libsqlite3-0,mime-support,netbase,readline-common,tzdata,libgcc1,libgomp1,libstdc++6,zlib1g,libjpeg62-turbo,libpng16-16,liblcm
s2-2,libfreetype6,fonts-dejavu-core,fontconfig-config,libfontconfig1,libuuid1,openjdk-11-jre-headless,openjdk-11-jdk-headless,dash,libc-bin,libpython2.7-minimal,libpython2.7-stdlib,python2.7-minimal$
libmpdec2,libpython3.7-minimal,libpython3.7-stdlib,libtinfo6,libuuid1,libncursesw6,python3-distutils,python3.7-minimal,libcurl4,libgssapi-krb5-2,libicu63,liblttng-ust0,libssl1.1,libunwind8,libuuid1,z
lib1g,curl,libcomerr2,libidn2-0,libk5crypto3,libkrb5-3,libldap-2.4-2,libldap-common,libsasl2-2,libnghttp2-14,libpsl5,librtmp1,libssh2-1,libkeyutils1,libkrb5support0,libunistring2,libgnutls30,libgmp10
,libhogweed4,libidn11,libnettle6,libp11-kit0,libffi6,libtasn1-6,libsasl2-modules-db,libgcrypt20,libgpg-error0,libacl1,libattr1,libselinux1,libpcre3,libbz2-1.0,liblzma5 --workspace-name package_bundle
_debian10)
ERROR: Analysis of target '//examples/nodejs:hello' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.059s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 6061 targets configured)
    currently loading: cc
    Fetching @com_github_google_go_containerregistry; Restarting. 6s
    Fetching @bazel_gazelle_go_repository_tools; fetching 6s
    Fetching @com_github_pkg_errors; Restarting. 5s
```
</p></details>

Can someone tell me what I am doing wrong here?

**Comment by chanseokoh** [comment]
The build instructions are [here](https://github.com/GoogleContainerTools/distroless/blob/master/CONTRIBUTING.md#how-to-build-and-test). You build `dpkg_parser.par`, not `dpkg_parser`. I am not sure about the Python version though.

**Comment by elsbrock** [comment]
Thank you. I tried it, but the last command failed:

```
$ bazel build //...
INFO: Analyzed 218 targets (92 packages loaded, 12218 targets configured).
INFO: Found 218 targets...
INFO: From ImageLayer base/static_debian9-layer.tar:
Duplicate file in archive: ./etc/os-release, picking first occurrence
INFO: From ImageLayer base/static_debian10-layer.tar:
Duplicate file in archive: ./etc/os-release, picking first occurrence
INFO: From Action java/cacerts_java_debian9.tar:
etc/ssl/
etc/ssl/certs/
etc/ssl/certs/java/
etc/ssl/certs/java/cacerts
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/503e0ccd57155320cc1238769cd87073/external/bazel_tools/tools/jdk/BUILD:346:14: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1862)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1851)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
        at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
        at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:337)
        at java.base/java.nio.file.Files.isSameFile(Files.java:1530)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1860)
        ... 14 more
INFO: Elapsed time: 479.874s, Critical Path: 98.61s
INFO: 72 processes: 72 linux-sandbox.
FAILED: Build did NOT complete successfully
``` 

I do not have a JRE installed, so I assume that it was obtained by Bazel.

**Comment by chanseokoh** [comment]
I don't really understand the whole Bazel toolchain thing, but I think the easiest fix is to install a local JDK.

https://github.com/google/mediapipe/issues/68
https://github.com/bazelbuild/bazel/issues/7304
https://github.com/bazelbuild/bazel/issues/6993

**Comment by chanseokoh** [comment]
Lacking further updates, I will assume the issue is resolved.
