### ISSUE TITLE
Accept returns duplicate client endpoints under load

### ISSUE THREAD

**Issue by Na3blis** [GoogleContainerTools/distroless#923]
When running spring boot 2.6.2 apps I frequently get these errors in the logs: 

```
java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:545) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

I'm currently running with the latest image as of Wednesday: gcr.io/distroless/java@sha256:59472c7fc8b0f50c2db7c64865ea7f18f4e73f7172d0f64531c7c69122c594f9

It's an OS level bug and a more detailed explanation can be found https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298

**Comment by sri-beerelly** [comment]
@Na3blis Did you find any fix for this issue? I am also running into the same issue on spring boot 2.5.8, which has the same tomcat version under high load. 

_Socket accept failed
java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:545) ~[tomcat-embed-core-9.0.56.jar!/:?]
at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78) ~[tomcat-embed-core-9.0.56.jar!/:?]
at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129) [tomcat-embed-core-9.0.56.jar!/:?]
at java.lang.Thread.run(Unknown Source) [?:?]_

**Comment by loosebazooka** [comment]
From the description of the bug, I don't think a fix for this could come from the distroless team unfortunately.
